# -*- coding: utf-8 -*-
"""
products.json을 web/assets/db.js 로 변환 — window.PRODUCTS_DB = {...}
이러면 file:// 로 index.html 직접 열어도 fetch 없이 동작.
"""
import json, os

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "data", "products.json")
PROD_DIR = os.path.join(ROOT, "products")
DST = os.path.join(ROOT, "web", "assets", "db.js")

db = json.load(open(SRC, encoding="utf-8"))

# 각 상품의 meta.json을 같이 임베드 — 상세페이지가 file://에서도 동작
metas = {}
for p in db["products"]:
    gid = p["goodsId"]
    mp = os.path.join(PROD_DIR, gid, "meta.json")
    if os.path.exists(mp):
        try:
            m = json.load(open(mp, encoding="utf-8"))
            # 상세 인포 이미지가 많아 용량 큼 — 필수 필드만
            metas[gid] = {
                "main_images":   m.get("main_images", []),
                "detail_images": m.get("detail_images", []),
                "specs":         m.get("specs", []),
                "specs_by_size": m.get("specs_by_size"),  # 매트리스 사이즈별 사양
                "prices":        m.get("prices", []),
                "options":       m.get("options"),
            }
        except Exception as e:
            print(f"  [warn] meta {gid}: {e}")

payload = json.dumps(db, ensure_ascii=False)
meta_payload = json.dumps(metas, ensure_ascii=False)
js = (
    "/* auto-generated by build_inline_db.py — DO NOT EDIT */\n"
    f"window.PRODUCTS_DB = {payload};\n"
    f"window.PRODUCTS_META = {meta_payload};\n"
)
with open(DST, "w", encoding="utf-8") as f:
    f.write(js)
print(f"[done] {len(db['products'])} products + {len(metas)} metas -> {DST} ({os.path.getsize(DST)/1024:.1f}KB)")
